### ISSUE TITLE
Fix PEP8 on 7.0 branch

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-reconcile#30]
I'm going to do it, so this is a message to avoid duplicating work.

**Comment by laetitia-gangloff** [comment]
Hello,

I see that you have replaced some osv.except_osv by orm.except_orm in try except during your pep8 issue. I think it is not a good idea for the compatibility. Because in some case openerp raise osv.except_osv and not orm.except_orm.

Sorry to come too late :(

Stack trace sample:
  File "/home/lga/openerp/addons-banking/account_statement_ext/statement.py", line 608, in _get_period
    periods = period_obj.find(cr, uid, dt=date, context=local_context)
  File "/home/lga/openerp/addons/account/account.py", line 1027, in find
    raise osv.except_osv(_('Error!'), _('There is no period defined for this date: %s.\nPlease create one.')%dt)
except_osv: (u'Error!', u'There is no period defined for this date: 2014-08-20.\nPlease create one.')

**Comment by bwrsandman** [comment]
Indeed, when catching, you must catch both except_orm and except_osv:

``` python
In [3]: try:
    raise osv.except_osv('', '')
except orm.except_orm:
    print('caught')
   ...:     
---------------------------------------------------------------------------
except_osv                                Traceback (most recent call last)
python_dev in <module>()
      1 try:
----> 2     raise osv.except_osv('', '')
      3 except orm.except_orm:
      4     print('caught')
      5 

except_osv: ('', '')
```

**Comment by pedrobaeza** [comment]
You're right, Laetitia, although improbable, because all launch exceptions in the module are with orm.except_orm, but here it is the fix BTW: #38

**Comment by laetitia-gangloff** [comment]
The stack trace sample come from a new installation. Maybe it is not the case for all try/except ;).
Thank you for the correction.

**Comment by bwrsandman** [comment]
PEP8 is clean on 7.0 so I will close this. Consider cleaning 6.1
