### ISSUE TITLE
account_reconcile_oca : Bank statement lines remain 'reconciled' in the reconciliation widget, even though I unreconciled the payment on the invoice

### ISSUE THREAD

**Issue by gva-acsone** [OCA/account-reconcile#554]
## Module
account_reconcile_oca

## Describe the issue
Bank statement lines remain 'reconciled' in the reconciliation screen, even though I (manually) unreconcile the related payment and the invoice. The bank statement line should be considered as 'unreconciled' and ready to reconcile with another invoice. 

## To Reproduce
**Affected versions**: 16

1. Open the reconciliation screen (bank statement lines)
2. Reconcile a payment with an open invoice. The bank statement line will be considered as 'reconciled'
3. Open the invoice and unreconcile the payment and the invoice
4. Re-open the reconciliation screen
5. Your payment is still considered as 'reconciled' (even though it isn't linked to any invoice / has no matching number....). 

Shouldn't this bank statement line be re-opened? 

Thanks for your answer.

**Comment by gva-acsone** [comment]
@etobella, what do you think? Many thanks

**Comment by etobella** [comment]
The same error happens with odoo EE (tested on runbot).

The only way to detect that a bank payment line needs reconciliation is to find that it still has a line with some suspense account, but when you unreconcile from the invoice, the change is not done (it is correct to keep it as it is IMO).

Also, imagine that you have an statement with multiple invoices related to the same line. What should we do when we unreconcile one of them? All of them are unreconciled?

I think it's easier to keep it the current implementation. We can add the comment on DESCRIPTION or USAGE in order to minimize errors with users

**Comment by pedrobaeza** [comment]
Not a bug. The important thing is that when you unreconcile a payment from its invoice, the **account entry is not removed**, so the statement line is still "neutralized" and accounted, so that part is correct. You have to do the reconciliation again from the invoice or through journal items.
