### ISSUE TITLE
[16.0] Reconcile Button is Missing

### ISSUE THREAD

**Issue by micihn** [OCA/account-reconcile#615]
## Module
account_reconcile_oca
account_statement_base

## Describe the bug
I just installed the account_reconcile_oca and account_statement_base
## To Reproduce
**Affected versions**: Odoo 16 Community Edition

1. Install a fresh odoo database
2. install OCA Reconcile Module

**Expected behavior**
![image](https://github.com/OCA/account-reconcile/assets/108042879/eb2de2e4-e602-4702-ada8-9af635f50cff)
It should look like this, right?
Please help @etobella
Thank you!

**Comment by etobella** [comment]
If you press the three dots, you can access the Transactions Menu from there.

**Comment by micihn** [comment]
Oh, yeah I see. So the Reconcile button like "Reconcile x Items" can't be shown?

**Comment by lk-eska** [comment]
I see that button and it works fine?

**Comment by lk-eska** [comment]
I think the real problem is with the "transactions" action. It takes directly to reconcile page. Then how do we see the list of transacations, delete them?

action_bank_statement_line_reconcile_all should open view account_statement_base.account_bank_statement_line_tree and there should be reconcile button on that form.

**Comment by lk-eska** [comment]
https://github.com/OCA/account-reconcile/pull/637 fixes this confusion.
