### ISSUE TITLE
Wrong amount displayed

### ISSUE THREAD

**Issue by Giacomoodoo** [OCA/account-reconcile#634]
<img width="477" alt="Screenshot 2024-02-29 alle 11 29 17" src="https://github.com/OCA/account-reconcile/assets/161711494/6acd2c22-4d22-4875-ba22-180bd537e244">

Reconcile works correctly but the amount is displayed wrong

**Comment by Giacomoodoo** [comment]
I saw that this is due to thousand separation inside the languages. I choose to use this: ' as thousand separation (ex. 4'316)
If I remove the thousand separation then it works correctly but I need to keep.

**Comment by luc-jean** [comment]
It is the same for Version [16.0]
It displays &#x27 instead of the thousand separator.

On the left side and on the bottom right, it is displayed correct:
LEFT: 
![image](https://github.com/OCA/account-reconcile/assets/147585574/a245636c-5ec2-436f-8846-41faa8fea6a9)
BOTTOM RIGHT: 
![image](https://github.com/OCA/account-reconcile/assets/147585574/543f3f10-ed10-4ae2-a9ca-68a1c0614bc5)

But for the top right, it does not display the thousand separator: 
TOP RIGHT: 
![image](https://github.com/OCA/account-reconcile/assets/147585574/4af1e4ce-77e7-4384-967f-6186318c7f7f)


Is there a way to correct this? Besides that: Thanks a lot for this brilliant module!

**Comment by luc-jean** [comment]
@Giacomoodoo have you found a solution yet?

**Comment by Giacomoodoo** [comment]
Hi there,

No, unfortunately not. I bought a new module in Odoo third app.

Not because your module wasn’t good but I needed to correct it because the customer was stressed.

Best regards,
Giacomo


On 22 maggio 2024 a 08:36:16, luc-jean ***@***.***) scritto:

@Giacomoodoo have you found a solution yet?

**Comment by pedrobaeza** [comment]
Well, instead of paying the developer of the OCA module to fix the bug, you decided to buy a non-free app for that, which probably is hijacking certain parts of open source modules...
